NAME=cer0

DIRECTORY_INCLUDE=include
DIRECTORY_LIBRARY=library
DIRECTORY_OBJECTS=objects
DIRECTORY_SOURCES=sources

FILE_LIBRARY=${DIRECTORY_LIBRARY}/${NAME}.o

FILES_SOURCES=${wildcard ${DIRECTORY_SOURCES}/*.c}
FILES_OBJECTS=${patsubst ${DIRECTORY_SOURCES}/%.c,${DIRECTORY_OBJECTS}/%.o,${FILES_SOURCES}}

CC=gcc
C_FLAGS=-O3 -I${DIRECTORY_INCLUDE}

LD=ld
LD_FLAGS=

${FILE_LIBRARY}: ${FILES_OBJECTS} ${DIRECTORY_LIBRARY}
	${LD} ${LD_FLAGS} -r ${FILES_OBJECTS} -o $@

${DIRECTORY_OBJECTS}/%.o: ${DIRECTORY_SOURCES}/%.c ${DIRECTORY_OBJECTS}
	${CC} ${C_FLAGS} -c $< -o $@

${DIRECTORY_LIBRARY}:
	mkdir -p ${DIRECTORY_LIBRARY}

${DIRECTORY_OBJECTS}:
	mkdir -p ${DIRECTORY_OBJECTS}

clean:
	-rm -r ${DIRECTORY_LIBRARY}
	-rm -r ${DIRECTORY_OBJECTS} 

