#ifndef constants_h
#define constants_h

#define CER0_TWO_PI M_PI * 2.0f

#define CER0_FREQUENCY_ROOT_STANDARD 440.0f
#define CER0_FREQUENCY_ROOT_MAGIC 432.0f
#define CER0_FREQUENCY_ROOT_SCIENTIFIC 430.54f

#define CER0_OCTAVE_MINIMUM 0
#define CER0_OCTAVE_MAXIMUM 10
#define CER0_OCTAVE_RANGE CER0_OCTAVE_MAXIMUM - CER0_OCTAVE_MINIMUM

#endif
