name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["core"]
jobs:
  continuous_integration_build:
    runs-on: macos-latest
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - name: checkout_cer0
        uses: actions/checkout@v4
        with:
          path: cer0
      - name: checkout_clic3
        uses: actions/checkout@v4
        with:
          path: clic3
          repository: alic3dev/clic3
      - name: make:clic3_dylib
        run: cd clic3 && make clic3_dylib
      - name: make:clic3_dynamic
        run: cd clic3 && make clic3_dynamic
      - name: make:cer0_objects
        run: cd cer0 && make cer0_objects
      - name: make:cer0_dylib
        run: cd cer0 && make cer0_dylib
      - name: make:cer0_dynamic
        run: cd cer0 && make cer0_dynamic
      - name: make:cer0_object
        run: cd cer0 && make cer0_object
      - name: make:cer0_static
        run: cd cer0 && make cer0_static
      - name: make:cer0_tools
        run: cd cer0 && make tools
