name: continuous_integration_build_ios
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["*"]
env:
  enabled_caching: 1
  enabled_caching_clic3: 1
  enabled_caching_math_c: 1
  key_cache_clic3: cache_clic3_ios_0_0_0
  key_cache_math_c: cache_math_c_ios_0_0_0
  target_device_version: 18.5
jobs:
  continuous_integration_build_ios:
    runs-on: macos-latest
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - name: checkout_cer0
        uses: actions/checkout@v4
        with:
          path: cer0
      - name: cache_restore_clic3
        id: cache_restore_clic3
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_clic3 == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: clic3
          key: ${{ env.key_cache_clic3 }}
      - name: cache_restore_math_c
        id: cache_restore_math_c
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_math_c == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: math_c
          key: ${{ env.key_cache_math_c }}
      - name: checkout_clic3
        if: steps.cache_restore_clic3.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          repository: alic3dev/clic3
          path: clic3
      - name: checkout_math_c
        if: steps.cache_restore_math_c.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          repository: alic3dev/math_c
          path: math_c
      - name: make:clic3_ios_dylib
        if: steps.cache_restore_clic3.outputs.cache-hit != 'true'
        run: cd clic3 && make clic3_ios_dylib target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:clic3_ios_dynamic
        if: steps.cache_restore_clic3.outputs.cache-hit != 'true'
        run: cd clic3 && make clic3_ios_dynamic target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:math_c_ios_dylib
        if: steps.cache_restore_math_c.outputs.cache-hit != 'true'
        run: cd math_c && make math_c_ios_dylib target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:math_c_ios_dynamic
        if: steps.cache_restore_math_c.outputs.cache-hit != 'true'
        run: cd math_c && make math_c_ios_dynamic target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:cer0_ios_objects
        run: cd cer0 && make cer0_ios_objects target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:cer0_ios_dylib
        run: cd cer0 && make cer0_ios_dylib target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:cer0_ios_dynamic
        run: cd cer0 && make cer0_ios_dynamic target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:cer0_ios_object
        run: cd cer0 && make cer0_ios_object target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: make:cer0_ios_static
        run: cd cer0 && make cer0_ios_static target_device_version=${{ env.target_device_version }} target_device=iphone
      - name: cache_save_clic3
        id: cache_save_clic3
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_clic3 == '1' && steps.cache_restore_clic3.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: clic3
          key: ${{ env.key_cache_clic3 }}
      - name: cache_save_math_c
        id: cache_save_math_c
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_math_c == '1' && steps.cache_restore_math_c.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: math_c
          key: ${{ env.key_cache_math_c }}

